# Generated by Django 2.2.7 on 2019-11-20 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('title', models.CharField(max_length=99)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('price', models.IntegerField()),
                ('writer', models.CharField(max_length=49)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('name', models.CharField(max_length=99)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=99)),
                ('password', models.CharField(max_length=99)),
                ('contact', models.CharField(max_length=29)),
                ('address', models.CharField(max_length=99)),
            ],
        ),
        migrations.CreateModel(
            name='adminUser',
            fields=[
                ('name', models.CharField(max_length=48)),
                ('email', models.CharField(max_length=98)),
                ('password', models.CharField(max_length=98)),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.book')),
                ('title', models.CharField(max_length=50)),
                ('price', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='featuredSellers',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.user')),
                ('bookCount', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='sellerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
        migrations.CreateModel(
            name='giveAway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.book')),
                ('buyerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyers', to='user.user')),
                ('sellerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sellers', to='user.user')),
            ],
            options={
                'unique_together': {('bookID', 'sellerID', 'buyerID')},
            },
        ),
        migrations.CreateModel(
            name='exchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyerBookID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyerBook', to='user.book')),
                ('buyerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to='user.user')),
                ('sellerBookID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sellerBook', to='user.book')),
                ('sellerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='user.user')),
            ],
            options={
                'unique_together': {('sellerBookID', 'buyerBookID', 'sellerID', 'buyerID')},
            },
        ),
        migrations.CreateModel(
            name='bids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.book')),
                ('buyerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'unique_together': {('bookID', 'buyerID')},
            },
        ),
    ]
