# Generated by Django 2.2.7 on 2019-11-27 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='login.user'),
        ),
        migrations.AlterField(
            model_name='bids',
            name='buyerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.user'),
        ),
        migrations.AlterField(
            model_name='book',
            name='sellerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.user'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='buyerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to='login.user'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='sellerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='login.user'),
        ),
        migrations.AlterField(
            model_name='featuredsellers',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='login.user'),
        ),
        migrations.AlterField(
            model_name='giveaway',
            name='buyerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyers', to='login.user'),
        ),
        migrations.AlterField(
            model_name='giveaway',
            name='sellerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sellers', to='login.user'),
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
