# Generated by Django 2.2.7 on 2019-11-28 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20191127_2238'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bids',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='bids',
            name='bookID',
        ),
        migrations.RemoveField(
            model_name='bids',
            name='buyerID',
        ),
        migrations.RemoveField(
            model_name='book',
            name='sellerID',
        ),
        migrations.AlterUniqueTogether(
            name='exchange',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='exchange',
            name='buyerBookID',
        ),
        migrations.RemoveField(
            model_name='exchange',
            name='buyerID',
        ),
        migrations.RemoveField(
            model_name='exchange',
            name='sellerBookID',
        ),
        migrations.RemoveField(
            model_name='exchange',
            name='sellerID',
        ),
        migrations.AlterUniqueTogether(
            name='giveaway',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='giveaway',
            name='bookID',
        ),
        migrations.RemoveField(
            model_name='giveaway',
            name='buyerID',
        ),
        migrations.RemoveField(
            model_name='giveaway',
            name='sellerID',
        ),
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.book'),
        ),
        migrations.DeleteModel(
            name='adminUser',
        ),
        migrations.DeleteModel(
            name='bids',
        ),
        migrations.DeleteModel(
            name='book',
        ),
        migrations.DeleteModel(
            name='exchange',
        ),
        migrations.DeleteModel(
            name='giveAway',
        ),
    ]
