# Generated by Django 2.2.7 on 2019-12-06 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20191128_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.CharField(default='/media/images/home/default_book.jpg', max_length=149),
        ),
    ]
